In [19]:
import os
from kaggle.api.kaggle_api_extended import KaggleApi

os.environ['KAGGLE_USERNAME'] = 'ahga17'
os.environ['KAGGLE_KEY'] = 'cffdda7287a803acf8cb90f4ae429761'

# start API client
api = KaggleApi()
api.authenticate()

# path for download
download_path = 'C:/Users/Alonzo/Documents/Projects/Neuronix/archive'

# check if dataset already exists
if not os.path.exists(download_path) or not os.listdir(download_path):
    api = KaggleApi()
    api.authenticate()

    # download dataset if not there
    print("Downloading dataset...")
    api.dataset_download_files('kaggle/kaggle-survey-2017', path=download_path, unzip=True)
    print("Download complete.")
else:
    print("Dataset already exists at the specified path.")

Dataset already exists at the specified path.


In [2]:
# libraries
import numpy as np
import matplotlib.pyplot as plt
import random
import torch
import torch.optim as optim

matrix = np.array([[1, 2, 3], [4, 5, 6]]) #normal matrix
zero_matrix = np.zeros((3, 3)) # all zeroes matrix
identity_matrix = np.eye(3) # identity matrix
random_matrix = np.random.random((3, 3)) # nxm matrix (n, m) with random values

In [3]:
element = matrix[0, 1] # get ther element in first row, second column
row = matrix[1, :] # gets all second row
column = matrix[:, 2] # gets all third column

In [4]:
print(matrix)
print()
print(zero_matrix)
print()
print(identity_matrix)
print()
print(random_matrix)

[[1 2 3]
 [4 5 6]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0.81750428 0.57892763 0.92942215]
 [0.40811599 0.2272863  0.85665854]
 [0.82021235 0.49785879 0.66516968]]


In [5]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# addiction
addition = matrix1 + matrix2
subtraction = matrix1 - matrix2

print(addition)
print(subtraction)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [6]:
multiplication = np.dot(matrix1, matrix2)
print(multiplication)

[[19 22]
 [43 50]]


In [7]:
element_mult = matrix1 * matrix2
print(element_mult)

[[ 5 12]
 [21 32]]


In [8]:
transpose = matrix1.T
print(transpose)

[[1 3]
 [2 4]]


In [9]:
inverse = np.linalg.inv(matrix1)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
determinant = np.linalg.det(matrix1)
print(int(determinant))

-2


In [11]:
eigenvalues, eigenvectors = np.linalg.eig(matrix1)
print(eigenvalues, eigenvectors)

[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [12]:
# reshaping a matrix 
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# shift matrix
reshape_matrix = matrix.reshape(9)

# put the matrix back
#reshape_back = reshape_matrix.reshape(3, 3)

print(reshape_matrix)

[1 2 3 4 5 6 7 8 9]


In [13]:
print(matrix)
submatrix = matrix[0:2, 0:2] # [first 2 spots in row, first 2 spots in column]
print()
print(submatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]]


In [14]:
# adds random numbers to the matrix
num = random.randint(1, 50)
add_matrix = matrix + num
print(add_matrix)

[[17 18 19]
 [20 21 22]
 [23 24 25]]


In [15]:
# find rank 
rank = np.linalg.matrix_rank(matrix)
print(rank)

2


In [16]:
# 3D matrix
matrix_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
                    ])
print(matrix_3d)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [17]:
# 3d matrix with random values 1 -50
random_3d = np.random.randint(1, 50, (4, 4, 3))

print(random_3d)


[[[38 24 31]
  [22 35 29]
  [ 6 36 14]
  [ 7 48 15]]

 [[ 3 21  3]
  [24  9 26]
  [26 30 37]
  [44 25 19]]

 [[ 2 13 27]
  [ 1 30 10]
  [32 11 37]
  [15 36 31]]

 [[31 33 13]
  [19 39 32]
  [14  8 39]
  [42 29 18]]]
